logging:
    level:
        com:
            capg:
                mgs:
                    controller: TRACE
        root: INFO
server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Qwer@1234
        url: jdbc:mysql://localhost:3306/codejavadb
        username: root
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
                globally_quoted_identifiers: true
        show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    devtools:
      add-properties: true
#    security:
#      user:
#          name: root
#          password: qwer1234


#springfox:
#    documentation:
#        swagger:
#            v2:
#                ui:
#                    SwaggerUiConfigUiProperties:
#                        description: API documentation for my Spring Boot application
#                        title: My API Documentation
